languageCode = "ko"
languageName = "Korean"
weight = 1
title = "택스코드"
contentDir = 'content/ko'

[params]
  displayName = "Korean"
  isoCode = "ko"
  rtl = false
  # logo = "img/logo.png"
  description = "Taxcode website"
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2006년 1월 2일"

[params.author]
  name = "이준영 세무회계 사무소"
  headline = "사업자들이 꼭 알아야하는 쉽고 명쾌한 세금 정보"
  bio = "A little bit about you"
#   links = [
#     { link = "https://nunocoracao.github.io/blowfish/" },
#     { github = "https://github.com/nunocoracao/blowfish" },
#     { x-twitter = "https://twitter.com/burufugu" }
#   ]